project_id = "xwglcduyzyfmknmmwqdc"

[api]
enabled = true

[db]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
enabled = true
[edge_functions.create-client-with-auth]
verify_jwt = true
