
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdywdodbnmxavqleccwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1keXdkb2Ribm14YXZxbGVjY3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNzQ1NTIsImV4cCI6MjA1OTg1MDU1Mn0.G6GPlNrN_nHX-1GcfSohCA2c4aT8DeDyOiRfrzJoFv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'client-hub-access-auth-storage',
    // Add admin methods
    detectSessionInUrl: true,
  }
});
